# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('concentration', models.FloatField()),
                ('volume', models.FloatField()),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SolidEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('reagent_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagents.Reagent')),
            ],
        ),
        migrations.AddField(
            model_name='liquidentry',
            name='reagent_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagents.Reagent'),
        ),
    ]
