# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0002_auto_20160916_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liquidentry',
            options={'verbose_name': 'liquid'},
        ),
        migrations.AlterModelOptions(
            name='reagent',
            options={'verbose_name_plural': 'substances and reagents'},
        ),
        migrations.AlterModelOptions(
            name='solidentry',
            options={'verbose_name': 'solid'},
        ),
        migrations.AlterField(
            model_name='liquidentry',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date of usage'),
        ),
        migrations.AlterField(
            model_name='solidentry',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date of usage'),
        ),
    ]
